# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTZlPUGNyZDZaGqbOTc6w4EnPgRKHBuo

### Fungsi Keanggotaan
"""

def trapezoid(x, a, b, c, d):
    if x <= a or x >= d:
        return 0
    elif b <= x <= c:
        return 1
    elif a < x < b:
        return (x - a) / (b - a)
    else:
        return (d - x) / (d - c)

def triangle(x, a, b, c):
    if x <= a or x >= c:
        return 0
    elif x == b:
        return 1
    elif a < x < b:
        return (x - a) / (b - a)
    else:
        return (c - x) / (c - b)

"""Fuzzifikasi

Mengubah nilai tegas menjadi nilai fuzzy
"""

def fuzzifikasi(harga, jarak, fasilitas):
    return {
        "harga_murah": trapezoid(harga, 0, 0, 400, 600),
        "harga_sedang": triangle(harga, 500, 700, 900),
        "harga_mahal": trapezoid(harga, 800, 900, 1000, 1000),

        "jarak_dekat": trapezoid(jarak, 0, 0, 0.5, 1.5),
        "jarak_sedang": triangle(jarak, 1, 2.5, 4),
        "jarak_jauh": trapezoid(jarak, 3, 4, 5, 5),

        "fasilitas_kurang": trapezoid(fasilitas, 0, 0, 30, 50),
        "fasilitas_cukup": triangle(fasilitas, 40, 60, 80),
        "fasilitas_lengkap": trapezoid(fasilitas, 70, 85, 100, 100)
    }

"""### Inferensi Fuzzy (aturan)"""

def inferensi(fz):
    tidak_layak = max(
        min(fz["harga_mahal"], fz["jarak_jauh"]),
        fz["fasilitas_kurang"]
    )

    layak = min(
        max(fz["harga_murah"], fz["harga_sedang"]),
        max(fz["jarak_dekat"], fz["jarak_sedang"]),
        fz["fasilitas_cukup"]
    )

    sangat_layak = min(
        max(fz["harga_murah"], fz["harga_sedang"]),
        fz["jarak_dekat"],
        fz["fasilitas_lengkap"]
    )

    return tidak_layak, layak, sangat_layak

"""### Defuzzifikasi (Metode Centroid)"""

def defuzzifikasi(tl, l, sl):
    numerator = 0
    denominator = 0

    for x in range(0, 101):
        mu_tl = min(tl, trapezoid(x, 0, 0, 30, 50))
        mu_l = min(l, triangle(x, 40, 60, 80))
        mu_sl = min(sl, trapezoid(x, 70, 85, 100, 100))

        mu = max(mu_tl, mu_l, mu_sl)

        numerator += x * mu
        denominator += mu

    return numerator / denominator if denominator != 0 else 0

"""### Main Program"""

import csv

hasil = []

with open("DATASET.csv", newline="") as file:
    reader = csv.reader(file)

    header_row = next(reader)

    if len(header_row) == 1 and ',' in header_row[0]:
        column_names = header_row[0].split(',')
    else:
        column_names = header_row

    col_indices = {name: i for i, name in enumerate(column_names)}

    for row_data_list in reader:
        if len(row_data_list) == 1 and ',' in row_data_list[0]:
            current_row_values = row_data_list[0].split(',')
        else:
            current_row_values = row_data_list

        if len(current_row_values) != len(column_names):
            print(f"Skipping malformed row due to incorrect column count: {row_data_list}")
            continue

        try:
            id_kost = current_row_values[col_indices["id_kost"]]
            harga = float(current_row_values[col_indices["harga"]])
            jarak = float(current_row_values[col_indices["jarak_kampus"]])
            fasilitas = float(current_row_values[col_indices["fasilitas"]])
        except (KeyError, ValueError) as e:
            print(f"Error processing row {current_row_values}: {e}. Skipping row.")
            continue

        fz = fuzzifikasi(harga, jarak, fasilitas)
        tl, l, sl = inferensi(fz)
        skor = defuzzifikasi(tl, l, sl)

        hasil.append([
            id_kost,
            harga,
            jarak,
            fasilitas,
            round(skor, 2)
        ])

hasil.sort(key=lambda x: x[4], reverse=True)

#Simpan Hasil ke File CSV
with open("DATASET_ranked.csv", "w", newline="") as out:
    writer = csv.writer(out)
    writer.writerow(["ID Kost", "Harga", "Jarak", "Fasilitas", "Skor Kelayakan"])
    for data in hasil:
        writer.writerow(data)

#Menampilkan 5 Kost Terbaik
print("5 KOST TERBAIK:")
for i in range(5):
    if i < len(hasil):
        print(hasil[i])
    else:
        break